Repository U-Me-Chan/umechan, pull requests merged in 2025-03, with the labels that each got.

#63 [#62] Радио: Метрики: Зарефакторено
  docker-compose.dev.yml
  docker-compose.prod.yml
  images/Dockerfile.api
  images/Dockerfile.filestore
  images/Dockerfile.radio-db-importer
  images/Dockerfile.radio-metrics
  images/Dockerfile.radio-scheduler
  radio-metrics/composer.lock
  radio-metrics/index.php
  radio-metrics/src/Cache/Memcached.php
  radio-metrics/src/Cache/Memory.php
  radio-metrics/src/Collectors/IcecastCollector.php
  radio-metrics/src/Http/Controllers/EstimateTrack.php
  radio-metrics/src/Http/Controllers/GetInfo.php
  radio-metrics/src/ICache.php
  radio-metrics/src/ISender.php
  radio-metrics/src/SenderProvider.php
  radio-metrics/src/Senders/ChanSender.php
  radio-metrics/src/Senders/DiscordWebHookSender.php
  radio-metrics/src/Senders/DummySender.php
  radio-metrics/src/Storage/DbConnector.php
  radio-metrics/src/TickHandler.php
  radio-metrics/src/Utils/Container.php
  radio-metrics/testing.sh
  radio-metrics/tests/Cache/MemoryTest.php
  radio-metrics/tests/Collectors/IcecastCollectorTest.php
  radio-metrics/tests/DatabaseTestCase.php
  radio-metrics/tests/Storage/Entities/TrackTest.php
  radio-metrics/tests/Storage/RecordRepositoryTest.php
  radio-metrics/tests/Storage/TrackRepositoryTest.php
  radio-metrics/tests/TickHandlerTest.php
Labels: рефакторинг

#66 Радио: Планировщик: Добавлена OpenAPI-спецификация для публичного API, а также интерфейс её просмотра
  images/Dockerfile.radio-scheduler
  radio-scheduler/composer.json
  radio-scheduler/composer.lock
  radio-scheduler/index.php
  radio-scheduler/phpstan.neon
  radio-scheduler/src/Http/Controllers/GetOpenApiSpecifitation.php
  radio-scheduler/src/Http/Controllers/GetQueue.php
  radio-scheduler/src/Http/Controllers/GetRedocPage.php
  radio-scheduler/src/Http/Controllers/GetTrackList.php
  radio-scheduler/src/Http/Controllers/OrderTrack.php
  radio-scheduler/src/Http/OpenApi/Schemas/Queue.php
  radio-scheduler/src/Http/OpenApi/Schemas/QueueTrack.php
  radio-scheduler/src/Http/OpenApi/Schemas/Track.php
  radio-scheduler/src/Http/Router.php
Labels: новая функциональность

#67 Чан: Frontend: Form: Добавить возможность вставки изображений из буфера обмена в форму отправки поста
  frontend/src/components/Form.vue
  frontend/src/constants/common-error-texts.js
Labels: новая функциональность

#82 Инфраструктура: Исправлен путь до тома с логами веб-сервера
  .gitignore
  docker-compose.yml
Labels: ошибки
