Repository U-Me-Chan/umechan, pull requests merged in 2025-02, with the labels that each got.

#44 Чан: Frontend && API: Добавлена поддержка видеоконтента в парсере ссылок и клиентском приложении
  api/src/Posts/Post.php
  api/src/Posts/Post/ImageParser.php
  api/src/Posts/Post/Post.php
  api/src/Posts/Post/VideoParser.php
  api/src/Posts/Post/YoutubeParser.php
  api/src/Posts/PostStorage.php
  api/src/Utils/PostMessageParser.php
  api/tests/Posts/Post/ImageParserTest.php
  api/tests/Posts/Post/VideoParserTest.php
  api/tests/Posts/Post/YoutubeParserTest.php
  docker-compose.dev.yml
  docker-compose.prod.yml
  filestore/src/Services/FileUploader.php
  frontend/src/components/Board.vue
  frontend/src/components/Board/Thread.vue
  frontend/src/components/Post.vue
  frontend/src/components/Post/Media.vue
  frontend/src/components/Post/Media/Video.vue
  frontend/src/components/Thread.vue
Labels: новая функциональность

#47 Frontend: Возникновение горизонтального оверфлоу оболочки тредов при загрузке постов, содержащих много текста без вайтспейсов.
  frontend/src/components/App.vue
  frontend/src/components/AuthPanel.vue
  frontend/src/components/Form.vue
  frontend/src/components/Radio.vue
  frontend/src/components/Thread.vue
Labels: ошибки, новая функциональность

#49 Чан: Frontend: Board: Исправление дефектов отображения обьектов визуального обособления пагинаторов от основного контента борды
  frontend/src/components/Board.vue
Labels: ошибки

#48 Чан: Frontend: App: Исправление горизонтальных сползаний хедера и…
  frontend/src/components/App.vue
Labels: ошибки

#50 Чан: Frontend: Board: Исправлено наличие дефолтного margin-bottom у верхнего пагинатора борды
  frontend/src/components/Board.vue
Labels: ошибки

#51 Чан: Frontend: Исправление отсутствия переноса безвайтспейсовых блобов эмоджи-текста
  frontend/src/components/Board.vue
  frontend/src/components/Thread.vue
Labels: ошибки

#52 Frontend: Визуальные исправления стадии загрузки контента страницы при первом открытии
  frontend/src/components/App.vue
Labels: ошибки

#56 Чан: API: Добавлена поддержка формата изображений JFIF для парсера медиа [#54]
  api/src/Posts/Post/ImageParser.php
  api/tests/Posts/Post/ImageParserTest.php
Labels: новая функциональность

#57 [#55] Радио: Клиент: Удалён лоадер при загрузке очереди
  frontend/src/components/Tracks.vue
Labels: ошибки

#58 [#53] Чан: Клиент: Форма отправки сообщения теперь допускает drag-n-drop для загрузки файла
  frontend/src/components/Form.vue
Labels: новая функциональность
